namespace Alchemy
{
    [ObjectAttr(488, 8)]
    public class CGlobalTuningData : igObject
    {
        [FieldAttr(16)] public CGlobalRenderData? _renderData;
        [FieldAttr(24)] public float _wingedSapphireDiscount = 0.02f;
        [FieldAttr(28)] public float _railSameRailJumpHeight = 300.0f;
        [FieldAttr(32)] public float _railSameRailJumpTime = 1.0f;
        [FieldAttr(36)] public float _railChangeRailsJumpHeight = 300.0f;
        [FieldAttr(40)] public float _railChangeRailsJumpTime = 1.0f;
        [FieldAttr(44)] public float _railJumpStickMagnitudeThreshold = 0.25f;
        [FieldAttr(48)] public float _railJumpStickAngleThreshold = 120.0f;
        [FieldAttr(52)] public float _railDistanceBetweenPlayers = 250.0f;
        [FieldAttr(56)] public float _railDistanceBetweenPlayersBuffer = 50.0f;
        [FieldAttr(60)] public float _railPlayerCatchupTime = 1.0f;
        [FieldAttr(64)] public float _railLeaderTransitionTime = 1.0f;
        [FieldAttr(68)] public float _minDelayTillDynamicCollectiblesAreCollectible = 1.0f;
        [FieldAttr(72)] public float _maxDelayTillDynamicCollectiblesAreCollectible = 1.29999995f;
        [FieldAttr(76)] public float _xpMultiplierPerLevelBelowTarget = 0.25f;
        [FieldAttr(80)] public float _xpMultiplierMax = 3.0f;
        [FieldAttr(84)] public int _xpMultiplierMapLevelOffset;
        [FieldAttr(88)] public float _enemyDamageCoopScale = 1.25f;
        [FieldAttr(92)] public float _enemyHealthCoopScale = 1.39999998f;
        [FieldAttr(96)] public CDifficultySpecificFloat? _difficultyFixedEnemyDamageScale;
        [FieldAttr(104)] public CDifficultySpecificFloat? _difficultyFixedEnemyHealthScale;
        [FieldAttr(112)] public CDifficultySpecificInt? _difficultyFoodHealthGainPercentage;
        [FieldAttr(120)] public CDifficultySpecificInt? _difficultyShieldRepairGainPercentage;
        [FieldAttr(128)] public CDifficultySpecificFloat? _difficultyLevelUpHealthRecovery;
        [FieldAttr(136)] public CDifficultySpecificFloat? _difficultyEnemyAttackCooldownMultiplier;
        [FieldAttr(144)] public CDifficultySpecificFloat? _difficultyAirChaseCooldownMultiplier;
        [FieldAttr(152)] public float _foodDropMediumHealthThreshold = 0.8f;
        [FieldAttr(156)] public float _foodDropLowHealthThreshold = 0.4f;
        [FieldAttr(160)] public CDifficultySpecificFloat? _foodDropCooldown;
        [FieldAttr(168)] public CDifficultySpecificInt? _foodDropNormalChance;
        [FieldAttr(176)] public CDifficultySpecificInt? _foodDropMediumHealthChance;
        [FieldAttr(184)] public CDifficultySpecificInt? _foodDropLowHealthChance;
        [FieldAttr(192)] public float _shieldDropLowShieldsThreshold = 0.4f;
        [FieldAttr(200)] public CDifficultySpecificFloat? _shieldDropCooldown;
        [FieldAttr(208)] public CDifficultySpecificInt? _shieldDropNormalChance;
        [FieldAttr(216)] public CDifficultySpecificInt? _shieldDropLowShieldsChance;
        [FieldAttr(224)] public float _difficultyBaseSkillLevel = 5.0f;
        [FieldAttr(232)] public CDifficultySpecificFloat? _difficultyMinSkillLevel;
        [FieldAttr(240)] public CDifficultySpecificFloat? _difficultyMaxSkillLevel;
        [FieldAttr(248)] public float _difficultyHealthModifierStrength = 0.5f;
        [FieldAttr(252)] public float _difficultyDamageModifierStrength = 1.0f;
        [FieldAttr(256)] public float _difficultyDamageTimeOut = 3.0f;
        [FieldAttr(260)] public float _difficultyIdleTimeOut = 12.0f;
        [FieldAttr(264)] public float _difficultyIncreasingSkillMultiplier = 2.0f;
        [FieldAttr(268)] public float _difficultyMaxDifficultyChange = 1.0f;
        [FieldAttr(272)] public float _difficultyAdditionalTimePerDeath = 5.0f;
        [FieldAttr(276)] public int _difficultyDeathCountForTrapdoor = 2;
        [FieldAttr(280)] public int _difficultyMaxTrapdoors = 2;
        [FieldAttr(284)] public float _difficultyTrapdoorSkillDecrease = 2.0f;
        [FieldAttr(288)] public float _defaultCritMultiplier = 150.0f;
        [FieldAttr(292)] public float _maxCritMultiplier = 200.0f;
        [FieldAttr(296)] public float _maxCritChance = 50.0f;
        [FieldAttr(304)] public igIntFloatHashTable? _levelHealthMultipliers;
        [FieldAttr(312)] public igIntFloatHashTable? _levelHealthMultipliersPVP;
        [FieldAttr(320)] public int _survivalAlmostPerfectLivesSolo = 4;
        [FieldAttr(324)] public int _survivalAlmostPerfectLivesCoop = 4;
        [FieldAttr(328)] public int _survivalAlmostPerfectLivesRival = 4;
        [FieldAttr(332)] public int _battleModeRewardBaseGold = 80;
        [FieldAttr(336)] public int _battleModeRewardBaseXP = 80;
        [FieldAttr(340)] public float _battleModeRewardGoldRewardMultiplier = 0.44999999f;
        [FieldAttr(344)] public float _battleModeRewardXPRewardMultiplier = 0.55f;
        [FieldAttr(348)] public int _battleModeRewardMaxLevelDifferenceNoModification = 2;
        [FieldAttr(352)] public int _battleModeRewardMaxLevelDifferenceModification = 6;
        [FieldAttr(356)] public float _battleModeRewardWinnerLevelLowerMultiplier = 1.39999998f;
        [FieldAttr(360)] public float _battleModeRewardWinnerLevelHigherMultiplier = 0.5f;
        [FieldAttr(364)] public igRangedFloatMetaField _battleModeRewardRandomValueToAdd = new();
        [FieldAttr(372)] public float _battleModeRewardLoserRatio = 0.5f;
        [FieldAttr(376)] public igVec2fList? _battleModeRewardTimeMultipliers;
        [FieldAttr(384)] public float _speedsterLeftRightTraversalSpeed = 200.0f;
        [FieldAttr(388)] public float _speedsterNormalGravity = 385.0f;
        [FieldAttr(392)] public float _speedsterAirStateGroundDistance = 100.0f;
        [FieldAttr(396)] public float _speedsterMaxFallSpeed = 600.0f;
        [FieldAttr(400)] public float _speedsterNormalSpeed = 1500.0f;
        [FieldAttr(404)] public float _speedsterJumpForce = 3000.0f;
        [FieldAttr(408)] public float _speedsterBoostSpeed = 2000.0f;
        [FieldAttr(412)] public float _speedsterBoostDuration = 3.0f;
        [FieldAttr(416)] public float _speedsterBoostCooldown = 15.0f;
        [FieldAttr(420)] public float _speedsterBoostAcceleration = 300.0f;
        [FieldAttr(424)] public float _speedsterBoostDeceleration = 300.0f;
        [FieldAttr(432)] public CBoltPoint? _speedsterBoostButtonPromptBolt;
        [FieldAttr(440)] public float _speedsterSlowSpeed = 500.0f;
        [FieldAttr(444)] public float _speedsterSlowDuration = 3.0f;
        [FieldAttr(448)] public float _speedsterSlowAcceleration = 300.0f;
        [FieldAttr(452)] public float _speedsterSlowDeceleration = 300.0f;
        [FieldAttr(456)] public float _speedsterSlowCooldown = 1.0f;
        [FieldAttr(460)] public float _speedsterMaxLeanAngle = 30.0f;
        [FieldAttr(464)] public float _speedsterLeanAngleSpeed = 60.0f;
        [FieldAttr(468)] public float _speedsterAttachmentSpawnRange = 1000.0f;
        [FieldAttr(472)] public float _superdropDeathFadeTime = 1.0f;
        [FieldAttr(476)] public float _forceForwardLeftRightTraversalSpeed = 200.0f;
        [FieldAttr(480)] public float _forceForwardMaxTwistAngle = 60.0f;
        [FieldAttr(484)] public float _forceForwardTwistSpeed = 300.0f;
    }
}
