namespace Alchemy
{
    // VSC object extracted from: common_Crash_Leaderboards_Root.igz

    [ObjectAttr(1048, metaType: typeof(igGuiVscBehavior))]
    public class common_Crash_Leaderboards_Root : igGuiVscBehavior
    {
        [FieldAttr(40)] public bool _Bool_0x28;
        [FieldAttr(48)] public igHandleMetaField _Localized_String_0x30 = new();
        [FieldAttr(56)] public igHandleMetaField _Gui_Animation_Tag_0x38 = new();
        [FieldAttr(64)] public igObject? _InternalStore_listener_0x40 = new();
        [FieldAttr(72)] public bool _Bool_0x48;
        [FieldAttr(80)] public igHandleMetaField _Gui_Animation_Tag_0x50 = new();
        [FieldAttr(88)] public igHandleMetaField _InternalStore_project_0x58 = new();
        [FieldAttr(96)] public igHandleMetaField _InternalStore_project_0x60 = new();
        [FieldAttr(104)] public igHandleMetaField _InternalStore_project_0x68 = new();
        [FieldAttr(112)] public int _Int_0x70;
        [FieldAttr(120)] public igObject? _Time_Trial_Leaderboard_Data_List_0x78 = new();
        [FieldAttr(128)] public igObject? _Time_Trial_Leaderboard_Data_List_0x80 = new();
        [FieldAttr(136)] public igObject? _Time_Trial_Leaderboard_Data_List_0x88 = new();
        [FieldAttr(144)] public igObject? _Time_Trial_Leaderboard_Data_List_0x90 = new();
        [FieldAttr(152)] public igObject? _Time_Trial_Leaderboard_Data_List_0x98 = new();
        [FieldAttr(160)] public int _InternalStore__internalCounter_0xa0;
        [FieldAttr(168)] public igHandleMetaField _InternalStore_project_0xa8 = new();
        [FieldAttr(176)] public igHandleMetaField _InternalStore_project_0xb0 = new();
        [FieldAttr(184)] public igHandleMetaField _Localized_String_0xb8 = new();
        [FieldAttr(192)] public igHandleMetaField _Localized_String_0xc0 = new();
        [FieldAttr(200)] public string? _String_0xc8 = null;
        [FieldAttr(208)] public string? _String_0xd0 = null;
        [FieldAttr(216)] public igHandleMetaField _Localized_String_0xd8 = new();
        [FieldAttr(224)] public igHandleMetaField _Localized_String_0xe0 = new();
        [FieldAttr(232)] public string? _String_0xe8 = null;
        [FieldAttr(240)] public int _Int_0xf0;
        [FieldAttr(248)] public igHandleMetaField _Gui_Placeable_0xf8 = new();
        [FieldAttr(256)] public igHandleMetaField _InternalStore_project_0x100 = new();
        [FieldAttr(264)] public bool _Bool_0x108;
        [FieldAttr(265)] public bool _Bool_0x109;
        [FieldAttr(266)] public bool _Bool_0x10a;
        [FieldAttr(272)] public igHandleMetaField _InternalStore_project_0x110 = new();
        [FieldAttr(280)] public igHandleMetaField _InternalStore_project_0x118 = new();
        [FieldAttr(288)] public igHandleMetaField _InternalStore_project_0x120 = new();
        [FieldAttr(296)] public igHandleMetaField _InternalStore_project_0x128 = new();
        [FieldAttr(304)] public igHandleMetaField _Gui_Animation_Tag_0x130 = new();
        [FieldAttr(312)] public igHandleMetaField _Gui_Placeable_0x138 = new();
        [FieldAttr(320)] public int _Int_0x140;
        [FieldAttr(324)] public int _Int_0x144;
        [FieldAttr(328)] public igHandleMetaField _Gui_Placeable_0x148 = new();
        [FieldAttr(336)] public int _Int_0x150;
        [FieldAttr(340)] public int _Int_0x154;
        [FieldAttr(344)] public igHandleMetaField _Gui_Placeable_0x158 = new();
        [FieldAttr(352)] public igHandleMetaField _Gui_Placeable_0x160 = new();
        [FieldAttr(360)] public int _Int_0x168;
        [FieldAttr(368)] public igHandleMetaField _Gui_Placeable_0x170 = new();
        [FieldAttr(376)] public igHandleMetaField _Gui_Placeable_0x178 = new();
        [FieldAttr(384)] public igHandleMetaField _Gui_Placeable_0x180 = new();
        [FieldAttr(392)] public igHandleMetaField _Gui_Placeable_id_l61tgmyl001 = new();
        [FieldAttr(400)] public igHandleMetaField _Gui_Shared_Asset_Project = new();
        [FieldAttr(408)] public igHandleMetaField _Gui_Placeable_0x198 = new();
        [FieldAttr(416)] public int _InternalStore__internalCounter_0x1a0;
        [FieldAttr(424)] public igObject? _Time_Trial_Leaderboard_Data_0x1a8 = new();
        [FieldAttr(432)] public igHandleMetaField _Gui_Animation_Tag_0x1b0 = new();
        [FieldAttr(440)] public int _InternalStore__internalCounter_0x1b8;
        [FieldAttr(448)] public igObject? _Time_Trial_Leaderboard_Data_0x1c0 = new();
        [FieldAttr(456)] public float _Float_0x1c8;
        [FieldAttr(460)] public float _Float_0x1cc;
        [FieldAttr(464)] public float _Float_0x1d0;
        [FieldAttr(468)] public float _Float_0x1d4;
        [FieldAttr(472)] public float _Float_0x1d8;
        [FieldAttr(476)] public igVec3fMetaField _Vector3 = new();
        [FieldAttr(488)] public float _Float_0x1e8;
        [FieldAttr(492)] public int _Int_0x1ec;
        [FieldAttr(496)] public igObject? _Gui_Placeable_List = new();
        [FieldAttr(504)] public igHandleMetaField _Gui_Placeable_0x1f8 = new();
        [FieldAttr(512)] public int _InternalStore__internalCounter_0x200;
        [FieldAttr(520)] public igHandleMetaField _Gui_Placeable_0x208 = new();
        [FieldAttr(528)] public int _Int_0x210;
        [FieldAttr(532)] public int _Int_0x214;
        [FieldAttr(536)] public int _Int_0x218;
        [FieldAttr(540)] public int _Int_0x21c;
        [FieldAttr(544)] public igHandleMetaField _Gui_Placeable_0x220 = new();
        [FieldAttr(552)] public igHandleMetaField _Gui_Placeable_0x228 = new();
        [FieldAttr(560)] public igHandleMetaField _Gui_Placeable_0x230 = new();
        [FieldAttr(568)] public igObject? _InternalStore_listener_0x238 = new();
        [FieldAttr(576)] public int _InternalStore__internalCounter_0x240;
        [FieldAttr(584)] public igHandleMetaField _Gui_Placeable_0x248 = new();
        [FieldAttr(592)] public igHandleMetaField _Gui_Placeable_0x250 = new();
        [FieldAttr(600)] public bool _Bool_0x258;
        [FieldAttr(604)] public int _Int_0x25c;
        [FieldAttr(608)] public int _Int_0x260;
        [FieldAttr(612)] public bool _Bool_0x264;
        [FieldAttr(616)] public igObject? _Time_Trial_Leaderboard_Data_0x268 = new();
        [FieldAttr(624)] public int _Int_0x270;
        [FieldAttr(628)] public int _Int_0x274;
        [FieldAttr(632)] public igHandleMetaField _Gui_Animation_Tag_0x278 = new();
        [FieldAttr(640)] public igHandleMetaField _Gui_Animation_Tag_0x280 = new();
        [FieldAttr(648)] public igHandleMetaField _Gui_Animation_Tag_0x288 = new();
        [FieldAttr(656)] public igHandleMetaField _Sound_0x290 = new();
        [FieldAttr(664)] public igHandleMetaField _Sound_0x298 = new();
        [FieldAttr(672)] public igHandleMetaField _Sound_0x2a0 = new();
        [FieldAttr(680)] public igHandleMetaField _Sound_0x2a8 = new();
        [FieldAttr(688)] public igHandleMetaField _Zone_Info = new();
        [FieldAttr(696)] public igHandleMetaField _Sound_0x2b8 = new();
        [FieldAttr(704)] public int _Int_0x2c0;
        [FieldAttr(708)] public int _Int_0x2c4;
        [FieldAttr(712)] public int _Int_0x2c8;
        [FieldAttr(720)] public igObject? _Time_Trial_Leaderboard_Data_List_0x2d0 = new();
        [FieldAttr(728)] public igHandleMetaField _Gui_Placeable_0x2d8 = new();
        [FieldAttr(736)] public int _Int_0x2e0;
        [FieldAttr(740)] public int _Int_0x2e4;
        [FieldAttr(744)] public igObject? _InternalStore_listener_0x2e8 = new();
        [FieldAttr(752)] public bool _Bool_0x2f0;
        [FieldAttr(760)] public igHandleMetaField _Gui_Animation_Tag_0x2f8 = new();
        [FieldAttr(768)] public igHandleMetaField _Gui_Animation_Tag_0x300 = new();
        [FieldAttr(776)] public igHandleMetaField _Localized_String_0x308 = new();
        [FieldAttr(784)] public igHandleMetaField _Sound_0x310 = new();
        [FieldAttr(792)] public igHandleMetaField _Game_Bool_Variable = new();
        [FieldAttr(800)] public bool _Bool_0x320;
        [FieldAttr(804)] public int _Int_0x324;
        [FieldAttr(808)] public int _Int_0x328;
        [FieldAttr(812)] public int _InternalStore__internalCounter_0x32c;
        [FieldAttr(816)] public igHandleMetaField _Gui_Placeable_0x330 = new();
        [FieldAttr(824)] public int _Int_0x338;
        [FieldAttr(832)] public igHandleMetaField _Gui_Placeable_0x340 = new();
        [FieldAttr(840)] public igHandleMetaField _Gui_Placeable_0x348 = new();
        [FieldAttr(848)] public igHandleMetaField _Gui_Placeable_0x350 = new();
        [FieldAttr(856)] public igHandleMetaField _Gui_Placeable_0x358 = new();
        [FieldAttr(864)] public igHandleMetaField _Gui_Placeable_0x360 = new();
        [FieldAttr(872)] public igHandleMetaField _Gui_Placeable_0x368 = new();
        [FieldAttr(880)] public igHandleMetaField _Gui_Placeable_0x370 = new();
        [FieldAttr(888)] public igHandleMetaField _Gui_Placeable_0x378 = new();
        [FieldAttr(896)] public igHandleMetaField _Gui_Placeable_0x380 = new();
        [FieldAttr(904)] public int _igIntMetaField334;
        [FieldAttr(908)] public int _igIntMetaField335;
        [FieldAttr(912)] public int _igIntMetaField336;
        [FieldAttr(916)] public int _igIntMetaField337;
        [FieldAttr(920)] public int _igIntMetaField338;
        [FieldAttr(928)] public string? _igStringMetaField339 = null;
        [FieldAttr(936)] public string? _igStringMetaField33a = null;
        [FieldAttr(944)] public string? _igStringMetaField33b = null;
        [FieldAttr(952)] public int _igIntMetaField3a9;
        [FieldAttr(956)] public int _igIntMetaField3aa;
        [FieldAttr(960)] public int _igIntMetaField3ab;
        [FieldAttr(964)] public int _igIntMetaField3ac;
        [FieldAttr(968)] public int _igIntMetaField3ad;
        [FieldAttr(976)] public string? _igStringMetaField3ae = null;
        [FieldAttr(984)] public string? _igStringMetaField3af = null;
        [FieldAttr(992)] public string? _igStringMetaField3b0 = null;
        [FieldAttr(1000)] public int _igIntMetaField41e;
        [FieldAttr(1004)] public int _igIntMetaField41f;
        [FieldAttr(1008)] public int _igIntMetaField420;
        [FieldAttr(1012)] public int _igIntMetaField421;
        [FieldAttr(1016)] public int _igIntMetaField422;
        [FieldAttr(1024)] public string? _igStringMetaField423 = null;
        [FieldAttr(1032)] public string? _igStringMetaField424 = null;
        [FieldAttr(1040)] public string? _igStringMetaField425 = null;
    }
}
