namespace Alchemy
{
    [ObjectAttr(912, 16)]
    public class CLandVehicleCamera : CCamera
    {
        [FieldAttr(416)] public float _vehicleFollowDistance = 700.0f;
        [FieldAttr(420)] public float _vehicleFollowHeight = 300.0f;
        [FieldAttr(424)] public float _vehicleLookAtHeight;
        [FieldAttr(428)] public bool _useSplinePitch;
        [FieldAttr(432)] public float _splinePitchOffset = 1000.0f;
        [FieldAttr(436)] public float _angleToStopFollowingVehicle = 90.0f;
        [FieldAttr(440)] public float _angleToStopLockingCamera = 90.0f;
        [FieldAttr(444)] public float _recenteringDampingFactor = 0.1f;
        [FieldAttr(448)] public float _recenteringFromVehicleDraggingCameraFactor;
        [FieldAttr(452)] public float _vehiclePitchDampingFactor = 0.2f;
        [FieldAttr(456)] public float _vehicleYawDampingFactor = 0.2f;
        [FieldAttr(460)] public float _fovDampingFactor = 0.1f;
        [FieldAttr(464)] public float _vehicleRollDampingFactor = 0.2f;
        [FieldAttr(468)] public float _averageUpDampingFactor = 0.025f;
        [FieldAttr(472)] public float _verticalDampingFactor = 0.3f;
        [FieldAttr(476)] public float _verticalLookDampingFactor = 0.1f;
        [FieldAttr(480)] public float _driftTimeToMaxAngle = 3.0f;
        [FieldAttr(484)] public float _addedAngleWhileDrifting = 45.0f;
        [FieldAttr(488)] public float _camDriftDampingFactor = 0.3f;
        [FieldAttr(492)] public float _minHorizontalVelocity = 4000.0f;
        [FieldAttr(496)] public float _maxHorizontalVelocity = 8000.0f;
        [FieldAttr(500)] public float _minVerticalVelocity = 1000.0f;
        [FieldAttr(504)] public float _maxVerticalVelocity = 3000.0f;
        [FieldAttr(508)] public float _horizontalVelocitySwitchDampingFactor = 0.2f;
        [FieldAttr(512)] public float _verticalVelocitySwitchDampingFactor = 0.2f;
        [FieldAttr(516)] public float _verticalAngleDampingFactor = 0.1f;
        [FieldAttr(520)] public float _verticalAngleApplicationFactor = 0.5f;
        [FieldAttr(524)] public float _horizontalVelocityDampingFactor = 0.2f;
        [FieldAttr(528)] public float _modelOverridePitchMultiplier = 0.5f;
        [FieldAttr(536)] public CVehicleCameraZoomCollision? _zoomCollision;
        [FieldAttr(544)] public CVehicleCameraPanCollision? _leftPanCollision;
        [FieldAttr(552)] public CVehicleCameraPanCollision? _rightPanCollision;
        [FieldAttr(560)] public bool _lockCameraWhileParked;
        [FieldAttr(564)] public float _parkedTimeBeforeCameraLock = 1.0f;
        [FieldAttr(568)] public float _maxSpeedAnglePitch = 14.0f;
        [FieldAttr(572)] public float _maxSpeedAddedFov = 10.0f;
        [FieldAttr(576)] public float _vehiclePitchDampingVelocity;
        [FieldAttr(580)] public float _vehicleYawDampingVelocity;
        [FieldAttr(584)] public float _vehicleYawCumulator;
        [FieldAttr(588)] public float _vehicleRollDampingVelocity;
        [FieldAttr(592)] public igVec3fMetaField _recenteringDampingVelocity = new();
        [FieldAttr(604)] public float _vehicleHeightDampingVelocity;
        [FieldAttr(608)] public igVec3fMetaField _previousDirectionFromVehicleToCameraXY = new();
        [FieldAttr(620)] public float _previousVehiclePitch;
        [FieldAttr(624)] public float _previousVehicleYaw;
        [FieldAttr(628)] public float _previousVehicleDampenedYaw;
        [FieldAttr(632)] public float _previousVehicleRoll;
        [FieldAttr(636)] public float _overrideFov = 1.39999998f;
        [FieldAttr(640)] public float _previousOverrideFov = 1.39999998f;
        [FieldAttr(644)] public float _fovDampingVelocity;
        [FieldAttr(648)] public EPlayerId _playerId = EPlayerId.EPLAYERID_NONE;
        [FieldAttr(652)] public igVec3fMetaField _averageVehicleUp = new();
        [FieldAttr(664)] public float _dampenedUpMove;
        [FieldAttr(668)] public float _upMoveDampingVelocity;
        [FieldAttr(672)] public igVec3fMetaField _upDampingVelocity = new();
        [FieldAttr(684)] public igVec3fMetaField _lastVehiclePos = new();
        [FieldAttr(696)] public float _lastTotalUpMove;
        [FieldAttr(700)] public float _dampenedHorizontalDirLookFactor;
        [FieldAttr(704)] public float _dampenedVerticalDirLookFactor;
        [FieldAttr(708)] public float _horizontalDirLookDampingVelocity;
        [FieldAttr(712)] public float _verticalDirLookDampingVelocity;
        [FieldAttr(716)] public float _dampenedVerticalAngle;
        [FieldAttr(720)] public float _verticalAngleDampingVelocity;
        [FieldAttr(724)] public igVec2fMetaField _lastHorizontalVelocity = new();
        [FieldAttr(732)] public igVec3fMetaField _dampenedHorizontalVelocity = new();
        [FieldAttr(744)] public igVec3fMetaField _horizontalVelocityDampingVelocity = new();
        [FieldAttr(756)] public float _dampenedVehicleVerticalAngle;
        [FieldAttr(760)] public float _vehicleVerticalAngleDampingVelocity;
        [FieldAttr(764)] public CTransformMetaField _transformWithoutModifiers = new();
        [FieldAttr(792)] public CTransformMetaField _previousCameraTransform = new();
        [FieldAttr(820)] public igVec3fMetaField _vehicleUpSmoothed = new();
        [FieldAttr(832)] public bool _useTargetPosition;
        [FieldAttr(836)] public float _currentVehicleFollowDistance;
        [FieldAttr(840)] public float _currentVehicleFollowHeight;
        [FieldAttr(844)] public float _currentVehicleLookatHeight;
        [FieldAttr(848)] public float _addedFovRadians;
        [FieldAttr(852)] public float _addedFollowDistance;
        [FieldAttr(856)] public float _addedFollowHeight;
        [FieldAttr(860)] public float _addedBoostFovRadians;
        [FieldAttr(864)] public float _addedBoostFollowDistance;
        [FieldAttr(868)] public float _addedBoostFollowHeight;
        [FieldAttr(872)] public float _lastDriftRotateAngle;
        [FieldAttr(876)] public float _lastDriftCurrentYaw;
        [FieldAttr(880)] public float _lastDriftRotateAngleVelocity;
        [FieldAttr(884)] public bool _wasDrifting;
        [FieldAttr(888)] public float _postDriftTimer = 1.0f;
        [FieldAttr(892)] public float _yawAddition;
        [FieldAttr(896)] public bool _zoomCollided;
        [FieldAttr(897)] public bool _leftPanCollided;
        [FieldAttr(898)] public bool _rightPanCollided;
        [FieldAttr(900)] public float _lastQuickDiveDeltaDepth;
        [FieldAttr(904)] public float _lastQuickDiveVelocity;
    }
}
