namespace Alchemy
{
    [ObjectAttr(1280, 16)]
    public class CVisualDataGroup : igObject
    {
        [FieldAttr(16)] public bool _sunColorState;
        [FieldAttr(17)] public bool _sunIntensityState;
        [FieldAttr(18)] public bool _sunAnglesState;
        [FieldAttr(19)] public bool _skyGradientIntensityState;
        [FieldAttr(20)] public bool _skySunIntensityState;
        [FieldAttr(21)] public bool _skySunSizeState;
        [FieldAttr(22)] public bool _skySunAnglesState;
        [FieldAttr(23)] public bool _skySunshaftColorState;
        [FieldAttr(24)] public bool _skySunshaftDecayState;
        [FieldAttr(25)] public bool _skySunshaftDensityState;
        [FieldAttr(26)] public bool _skySunshaftIntensityState;
        [FieldAttr(27)] public bool _skySunshaftFadeState;
        [FieldAttr(28)] public bool _skyFadeState;
        [FieldAttr(29)] public bool _skyFarBlendState;
        [FieldAttr(30)] public bool _skyNearParallaxState;
        [FieldAttr(31)] public bool _cloudsLightVerticalState;
        [FieldAttr(32)] public bool _cloudsLightWrapState;
        [FieldAttr(33)] public bool _cloudsLitScaleState;
        [FieldAttr(34)] public bool _cloudsDarkScaleState;
        [FieldAttr(35)] public bool _cloudsHighlightSizeState;
        [FieldAttr(36)] public bool _cloudsHighlightStrengthState;
        [FieldAttr(37)] public bool _cloudsHighlightColorState;
        [FieldAttr(38)] public bool _cloudsShadowSizeState;
        [FieldAttr(39)] public bool _cloudsShadowStrengthState;
        [FieldAttr(40)] public bool _cloudsShadowColorState;
        [FieldAttr(41)] public bool _cloudsHazeStrengthState;
        [FieldAttr(42)] public bool _cloudFadingNearOffsetState;
        [FieldAttr(43)] public bool _cloudFadingFarOffsetState;
        [FieldAttr(44)] public bool _cloudFadingHeightOffsetState;
        [FieldAttr(45)] public bool _shadowLocalInfluenceState;
        [FieldAttr(46)] public bool _shadowRangeState;
        [FieldAttr(47)] public bool _shadowFadeStartState;
        [FieldAttr(48)] public bool _shadowBiasState;
        [FieldAttr(49)] public bool _shadowSplitDistributionState;
        [FieldAttr(50)] public bool _shadowFadeState;
        [FieldAttr(51)] public bool _shadowJumpInfluenceState;
        [FieldAttr(52)] public bool _mobileShadowRangeState;
        [FieldAttr(53)] public bool _mobileShadowHeightOffsetState;
        [FieldAttr(54)] public bool _mobileShadowFarPlaneState;
        [FieldAttr(55)] public bool _ambientSpecularScaleState;
        [FieldAttr(56)] public bool _ambientDiffuseScaleState;
        [FieldAttr(57)] public bool _ambientBakeAmbientInfluenceState;
        [FieldAttr(58)] public bool _ambientBakeDirectInfluenceState;
        [FieldAttr(59)] public bool _bloomLuminanceCutoffState;
        [FieldAttr(60)] public bool _bloomScaleState;
        [FieldAttr(61)] public bool _cloudCoverScaleState;
        [FieldAttr(62)] public bool _cloudCoverTileSizeState;
        [FieldAttr(63)] public bool _cloudCoverSpeedState;
        [FieldAttr(64)] public bool _cloudCoverDirectionState;
        [FieldAttr(65)] public bool _fogStartState;
        [FieldAttr(66)] public bool _fogDensityState;
        [FieldAttr(67)] public bool _fogColorState;
        [FieldAttr(68)] public bool _fogSunColorState;
        [FieldAttr(69)] public bool _fogSunInfluenceState;
        [FieldAttr(70)] public bool _fogFarSkyIntensityState;
        [FieldAttr(71)] public bool _visibilityEntityRadiusState;
        [FieldAttr(72)] public bool _visibilityEntityDistanceAboveState;
        [FieldAttr(73)] public bool _visibilityEntityDistanceBelowState;
        [FieldAttr(74)] public bool _visibilityEntityOffsetState;
        [FieldAttr(75)] public bool _visibilityLightDistanceState;
        [FieldAttr(76)] public bool _visibilityLightRangeState;
        [FieldAttr(77)] public bool _visibilityDistanceCullVeryLowState;
        [FieldAttr(78)] public bool _visibilityDistanceCullLowState;
        [FieldAttr(79)] public bool _visibilityDistanceCullMediumState;
        [FieldAttr(80)] public bool _visibilityDistanceCullHighState;
        [FieldAttr(81)] public bool _visibilityDistanceCullFadeRangeState;
        [FieldAttr(82)] public bool _visibilityVfxCullDistanceState;
        [FieldAttr(83)] public bool _obscuredFadeState;
        [FieldAttr(84)] public bool _lodShaderDistanceState;
        [FieldAttr(85)] public bool _windGeneralStrengthState;
        [FieldAttr(86)] public bool _windGustFrequencyState;
        [FieldAttr(87)] public bool _windGustStrengthMinState;
        [FieldAttr(88)] public bool _windGustStrengthMaxState;
        [FieldAttr(89)] public bool _windGustDurationMinState;
        [FieldAttr(90)] public bool _windGustDurationMaxState;
        [FieldAttr(91)] public bool _vignetteStrengthState;
        [FieldAttr(92)] public bool _vignetteMidpointState;
        [FieldAttr(93)] public bool _vignetteWidthState;
        [FieldAttr(94)] public bool _colorGlobalExposureState;
        [FieldAttr(95)] public bool _colorGlobalHueState;
        [FieldAttr(96)] public bool _colorGlobalSaturationState;
        [FieldAttr(97)] public bool _colorGlobalBrightnessState;
        [FieldAttr(98)] public bool _colorGlobalContrastState;
        [FieldAttr(99)] public bool _colorGlobalTintState;
        [FieldAttr(100)] public bool _colorSeparableHueRedsState;
        [FieldAttr(101)] public bool _colorSeparableHueYellowsState;
        [FieldAttr(102)] public bool _colorSeparableHueGreensState;
        [FieldAttr(103)] public bool _colorSeparableHueCyansState;
        [FieldAttr(104)] public bool _colorSeparableHueBluesState;
        [FieldAttr(105)] public bool _colorSeparableHueMagentasState;
        [FieldAttr(106)] public bool _colorSeparableSaturationRedsState;
        [FieldAttr(107)] public bool _colorSeparableSaturationYellowsState;
        [FieldAttr(108)] public bool _colorSeparableSaturationGreensState;
        [FieldAttr(109)] public bool _colorSeparableSaturationCyansState;
        [FieldAttr(110)] public bool _colorSeparableSaturationBluesState;
        [FieldAttr(111)] public bool _colorSeparableSaturationMagentasState;
        [FieldAttr(112)] public bool _toonFadeState;
        [FieldAttr(113)] public bool _toonLineWidthState;
        [FieldAttr(114)] public bool _defocusFadeState;
        [FieldAttr(115)] public bool _defocusPlanesState;
        [FieldAttr(116)] public bool _waterSimulationFadeState;
        [FieldAttr(117)] public bool _vfxQualityState;
        [FieldAttr(118)] public bool _blendAll;
        [FieldAttr(128)] public igVec4fMetaField _sunColor = new();
        [FieldAttr(144)] public float _sunIntensity = 1.0f;
        [FieldAttr(148)] public igVec3fMetaField _sunAngles = new();
        [FieldAttr(160)] public bool _skyGradientState;
        [FieldAttr(164)] public igVfxRangedCurveMetaField _skyGradientRed = new();
        [FieldAttr(248)] public igVfxRangedCurveMetaField _skyGradientGreen = new();
        [FieldAttr(332)] public igVfxRangedCurveMetaField _skyGradientBlue = new();
        [FieldAttr(416)] public float _skyGradientIntensity = 1.0f;
        [FieldAttr(420)] public float _skySunIntensity = 10.0f;
        [FieldAttr(424)] public float _skySunSize = 0.15f;
        [FieldAttr(428)] public igVec3fMetaField _skySunAngles = new();
        [FieldAttr(448)] public igVec4fMetaField _skySunshaftColor = new();
        [FieldAttr(464)] public float _skySunshaftDecay = 0.98f;
        [FieldAttr(468)] public float _skySunshaftDensity = 1.0f;
        [FieldAttr(472)] public float _skySunshaftIntensity = 1.0f;
        [FieldAttr(476)] public float _skySunshaftFade = 1.0f;
        [FieldAttr(480)] public float _skyFade = 1.0f;
        [FieldAttr(496)] public igVec4fMetaField _skyFarBlend = new();
        [FieldAttr(512)] public float _skyNearParallax = 0.0625f;
        [FieldAttr(516)] public float _cloudsLightVertical = 0.5f;
        [FieldAttr(520)] public float _cloudsLightWrap = 0.6f;
        [FieldAttr(524)] public float _cloudsLitScale = 1.14999998f;
        [FieldAttr(528)] public float _cloudsDarkScale = 0.75f;
        [FieldAttr(532)] public float _cloudsHighlightSize = 0.2f;
        [FieldAttr(536)] public float _cloudsHighlightStrength = 0.2f;
        [FieldAttr(544)] public igVec4fMetaField _cloudsHighlightColor = new();
        [FieldAttr(560)] public float _cloudsShadowSize = 0.2f;
        [FieldAttr(564)] public float _cloudsShadowStrength = 0.2f;
        [FieldAttr(576)] public igVec4fMetaField _cloudsShadowColor = new();
        [FieldAttr(592)] public float _cloudsHazeStrength = 1.0f;
        [FieldAttr(596)] public float _cloudFadingNearOffset;
        [FieldAttr(600)] public float _cloudFadingFarOffset;
        [FieldAttr(604)] public float _cloudFadingHeightOffset = 64.0f;
        [FieldAttr(608)] public float _shadowLocalInfluence;
        [FieldAttr(612)] public float _shadowRange = 3000.0f;
        [FieldAttr(616)] public float _shadowFadeStart = 15000.0f;
        [FieldAttr(624)] public igVec4fMetaField _shadowBias = new();
        [FieldAttr(640)] public float _shadowSplitDistribution = 0.89999998f;
        [FieldAttr(644)] public float _shadowFade = 1.0f;
        [FieldAttr(648)] public float _shadowJumpInfluence = 1.0f;
        [FieldAttr(652)] public float _mobileShadowRange = 1000.0f;
        [FieldAttr(656)] public float _mobileShadowHeightOffset = 1000.0f;
        [FieldAttr(660)] public float _mobileShadowFarPlane = 1500.0f;
        [FieldAttr(664)] public float _ambientSpecularScale = 1.0f;
        [FieldAttr(668)] public float _ambientDiffuseScale = 1.0f;
        [FieldAttr(672)] public bool _ambientDiffuseColorState;
        [FieldAttr(676)] public igVfxRangedCurveMetaField _ambientDiffuseColorRed = new();
        [FieldAttr(760)] public igVfxRangedCurveMetaField _ambientDiffuseColorGreen = new();
        [FieldAttr(844)] public igVfxRangedCurveMetaField _ambientDiffuseColorBlue = new();
        [FieldAttr(928)] public bool _ambientAtmosphereEffectState;
        [FieldAttr(936)] public igHandleMetaField _ambientAtmosphereEffect = new();
        [FieldAttr(944)] public float _ambientBakeAmbientInfluence = 0.5f;
        [FieldAttr(948)] public float _ambientBakeDirectInfluence = 1.0f;
        [FieldAttr(952)] public float _bloomLuminanceCutoff = 5.0f;
        [FieldAttr(956)] public float _bloomScale = 1.0f;
        [FieldAttr(960)] public float _cloudCoverScale;
        [FieldAttr(964)] public float _cloudCoverTileSize = 1.0f;
        [FieldAttr(968)] public float _cloudCoverSpeed = 30.0f;
        [FieldAttr(972)] public igVec2fMetaField _cloudCoverDirection = new();
        [FieldAttr(980)] public float _fogStart;
        [FieldAttr(984)] public float _fogDensity = 0.001f;
        [FieldAttr(992)] public igVec4fMetaField _fogColor = new();
        [FieldAttr(1008)] public igVec4fMetaField _fogSunColor = new();
        [FieldAttr(1024)] public float _fogSunInfluence = 100.0f;
        [FieldAttr(1028)] public float _fogFarSkyIntensity = 50.0f;
        [FieldAttr(1032)] public float _visibilityEntityRadius = 1800.0f;
        [FieldAttr(1036)] public float _visibilityEntityDistanceAbove = 900.0f;
        [FieldAttr(1040)] public float _visibilityEntityDistanceBelow = 900.0f;
        [FieldAttr(1044)] public float _visibilityEntityOffset = 900.0f;
        [FieldAttr(1048)] public float _visibilityLightDistance = 3700.0f;
        [FieldAttr(1052)] public float _visibilityLightRange = 300.0f;
        [FieldAttr(1056)] public float _visibilityDistanceCullVeryLow = 4000.0f;
        [FieldAttr(1060)] public float _visibilityDistanceCullLow = 8000.0f;
        [FieldAttr(1064)] public float _visibilityDistanceCullMedium = 16000.0f;
        [FieldAttr(1068)] public float _visibilityDistanceCullHigh = 24000.0f;
        [FieldAttr(1072)] public float _visibilityDistanceCullFadeRange = 500.0f;
        [FieldAttr(1076)] public float _visibilityVfxCullDistance = 6000.0f;
        [FieldAttr(1080)] public float _obscuredFade = 0.25f;
        [FieldAttr(1084)] public float _lodShaderDistance = 1200.0f;
        [FieldAttr(1088)] public float _windGeneralStrength = 0.25f;
        [FieldAttr(1092)] public float _windGustFrequency = 0.1f;
        [FieldAttr(1096)] public float _windGustStrengthMin;
        [FieldAttr(1100)] public float _windGustStrengthMax = 0.6f;
        [FieldAttr(1104)] public float _windGustDurationMin = 1.0f;
        [FieldAttr(1108)] public float _windGustDurationMax = 3.0f;
        [FieldAttr(1112)] public float _vignetteStrength;
        [FieldAttr(1116)] public float _vignetteMidpoint = 1.0f;
        [FieldAttr(1120)] public float _vignetteWidth = 0.5f;
        [FieldAttr(1124)] public float _colorGlobalExposure;
        [FieldAttr(1128)] public float _colorGlobalHue;
        [FieldAttr(1132)] public float _colorGlobalSaturation;
        [FieldAttr(1136)] public float _colorGlobalBrightness;
        [FieldAttr(1140)] public float _colorGlobalContrast;
        [FieldAttr(1152)] public igVec4fMetaField _colorGlobalTint = new();
        [FieldAttr(1168)] public float _colorSeparableHueReds;
        [FieldAttr(1172)] public float _colorSeparableHueYellows;
        [FieldAttr(1176)] public float _colorSeparableHueGreens;
        [FieldAttr(1180)] public float _colorSeparableHueCyans;
        [FieldAttr(1184)] public float _colorSeparableHueBlues;
        [FieldAttr(1188)] public float _colorSeparableHueMagentas;
        [FieldAttr(1192)] public float _colorSeparableSaturationReds;
        [FieldAttr(1196)] public float _colorSeparableSaturationYellows;
        [FieldAttr(1200)] public float _colorSeparableSaturationGreens;
        [FieldAttr(1204)] public float _colorSeparableSaturationCyans;
        [FieldAttr(1208)] public float _colorSeparableSaturationBlues;
        [FieldAttr(1212)] public float _colorSeparableSaturationMagentas;
        [FieldAttr(1216)] public float _toonFade;
        [FieldAttr(1220)] public float _toonLineWidth = 1.5f;
        [FieldAttr(1224)] public float _defocusFade = 1.0f;
        [FieldAttr(1232)] public igVec4fMetaField _defocusPlanes = new();
        [FieldAttr(1248)] public float _waterSimulationFade = 1.0f;
        [FieldAttr(1252)] public float _vfxQuality = 1.0f;
        [FieldAttr(1256)] public igHandleMetaField _reflectionMarker = new();
        [FieldAttr(1264)] public igPlane? _reflectionPlane;
    }
}
