namespace Alchemy
{
    [ObjectAttr(nst: 640, ctr: 632, align: 4, metaType: typeof(igGuiVscBehavior))]
    public class Octane_Customization_Root : igGuiVscBehavior
    {
        [FieldAttr(nst: 48, ctr: 40)] public igHandleMetaField _Gui_Animation_Tag_0x28 = new();
        [FieldAttr(nst: 56, ctr: 48)] public igHandleMetaField _Gui_Placeable_0x30 = new();
        [FieldAttr(nst: 64, ctr: 56)] public bool _Bool_0x38;
        [FieldAttr(nst: 72, ctr: 64)] public igHandleMetaField _Gui_Animation_Tag_0x40 = new();
        [FieldAttr(nst: 80, ctr: 72)] public igHandleMetaField _Gui_Animation_Tag_0x48 = new();
        [FieldAttr(nst: 88, ctr: 80)] public igHandleMetaField _Gui_Animation_Tag_0x50 = new();
        [FieldAttr(nst: 96, ctr: 88)] public igHandleMetaField _Gui_Placeable_0x58 = new();
        [FieldAttr(nst: 104, ctr: 96)] public igHandleMetaField _Gui_Placeable_0x60 = new();
        [FieldAttr(nst: 112, ctr: 104)] public igHandleMetaField _Gui_Animation_Tag_0x68 = new();
        [FieldAttr(nst: 120, ctr: 112)] public igHandleMetaField _Gui_Animation_Tag_0x70 = new();
        [FieldAttr(nst: 128, ctr: 120)] public igHandleMetaField _Gui_Animation_Tag_0x78 = new();
        [FieldAttr(nst: 136, ctr: 128)] public igHandleMetaField _Gui_Animation_Tag_0x80 = new();
        [FieldAttr(nst: 144, ctr: 136)] public igHandleMetaField _Gui_Animation_Tag_0x88 = new();
        [FieldAttr(nst: 152, ctr: 144)] public bool _Bool_0x90;
        [FieldAttr(nst: 160, ctr: 152)] public igHandleMetaField _Gui_Animation_Tag_0x98 = new();
        [FieldAttr(nst: 168, ctr: 160)] public igHandleMetaField _Gui_Placeable_0xa0 = new();
        [FieldAttr(nst: 176, ctr: 168)] public bool _Bool_0xa8;
        [FieldAttr(nst: 184, ctr: 176)] public igHandleMetaField _Gui_Animation_Tag_0xb0 = new();
        [FieldAttr(nst: 192, ctr: 184)] public igObject? _InternalStore__timer = new();
        [FieldAttr(nst: 200, ctr: 192)] public bool _Bool_0xc0;
        [FieldAttr(nst: 208, ctr: 200)] public igHandleMetaField _Gui_Animation_Tag_0xc8 = new();
        [FieldAttr(nst: 216, ctr: 208)] public igHandleMetaField _Localized_String_0xd0 = new();
        [FieldAttr(nst: 224, ctr: 216)] public igHandleMetaField _Localized_String_0xd8 = new();
        [FieldAttr(nst: 232, ctr: 224)] public bool _Bool_0xe0;
        [FieldAttr(nst: 233, ctr: 225)] public bool _Bool_0xe1;
        [FieldAttr(nst: 240, ctr: 232)] public string? _String = null;
        [FieldAttr(nst: 248, ctr: 240)] public EPlayerId _E_Player_Id;
        [FieldAttr(nst: 256, ctr: 248)] public igHandleMetaField _Entity_0xf8 = new();
        [FieldAttr(nst: 264, ctr: 256)] public bool _Bool_0x100;
        [FieldAttr(nst: 272, ctr: 264)] public igHandleMetaField _InternalStore_project = new();
        [FieldAttr(nst: 280, ctr: 272)] public igHandleMetaField _Entity_0x110 = new();
        [FieldAttr(nst: 288, ctr: 280)] public igHandleMetaField _Localized_String_0x118 = new();
        [FieldAttr(nst: 296, ctr: 288)] public igHandleMetaField _Localized_String_0x120 = new();
        [FieldAttr(nst: 304, ctr: 296)] public igHandleMetaField _Localized_String_0x128 = new();
        [FieldAttr(nst: 312, ctr: 304)] public igHandleMetaField _Localized_String_0x130 = new();
        [FieldAttr(nst: 320, ctr: 312)] public bool _Bool_0x138;
        [FieldAttr(nst: 321, ctr: 313)] public bool _Bool_0x139;
        [FieldAttr(nst: 328, ctr: 320)] public igHandleMetaField _Gui_Placeable_0x140 = new();
        [FieldAttr(nst: 336, ctr: 328)] public igHandleMetaField _Localized_String_0x148 = new();
        [FieldAttr(nst: 344, ctr: 336)] public igHandleMetaField _Gui_Animation_Tag_0x150 = new();
        [FieldAttr(nst: 352, ctr: 344)] public bool _Bool_0x158;
        [FieldAttr(nst: 353, ctr: 345)] public bool _Bool_0x159;
        [FieldAttr(nst: 354, ctr: 346)] public bool _Bool_0x15a;
        [FieldAttr(nst: 360, ctr: 352)] public igHandleMetaField _Zone_Info_0x160 = new();
        [FieldAttr(nst: 368, ctr: 360)] public igHandleMetaField _Zone_Info_0x168 = new();
        [FieldAttr(nst: 376, ctr: 368)] public bool _Bool_0x170;
        [FieldAttr(nst: 377, ctr: 369)] public bool _Bool_0x171;
        [FieldAttr(nst: 378, ctr: 370)] public bool _Bool_0x172;
        [FieldAttr(nst: 379, ctr: 371)] public bool _Bool_0x173;
        [FieldAttr(nst: 384, ctr: 376)] public igObject? _InternalStore_prioritySetHandler_0x178 = new();
        [FieldAttr(nst: 392, ctr: 384)] public igHandleMetaField _Priority_Dsp_Override_Set_0x180 = new();
        [FieldAttr(nst: 400, ctr: 392)] public igHandleMetaField _Game_Sound_Music_Settings_0x188 = new();
        [FieldAttr(nst: 408, ctr: 400)] public igHandleMetaField _Game_Bool_Variable_0x190 = new();
        [FieldAttr(nst: 416, ctr: 408)] public igHandleMetaField _Localized_String_0x198 = new();
        [FieldAttr(nst: 424, ctr: 416)] public ECustomizationType _Gui_List_Item_Populator_Customization_Grid_E_Customization_Type;
        [FieldAttr(nst: 432, ctr: 424)] public igHandleMetaField _Localized_String_0x1a8 = new();
        [FieldAttr(nst: 440, ctr: 432)] public bool _Bool_0x1b0;
        [FieldAttr(nst: 448, ctr: 440)] public igHandleMetaField _Localized_String_0x1b8 = new();
        [FieldAttr(nst: 456, ctr: 448)] public igHandleMetaField _Localized_String_0x1c0 = new();
        [FieldAttr(nst: 464, ctr: 456)] public bool _Bool_0x1c8;
        [FieldAttr(nst: 465, ctr: 457)] public bool _Bool_0x1c9;
        [FieldAttr(nst: 466, ctr: 458)] public bool _Bool_0x1ca;
        [FieldAttr(nst: 472, ctr: 464)] public igHandleMetaField _Gui_Project = new();
        [FieldAttr(nst: 480, ctr: 472)] public bool _Bool_0x1d8;
        [FieldAttr(nst: 488, ctr: 480)] public igHandleMetaField _Gui_Animation_Tag_0x1e0 = new();
        [FieldAttr(nst: 496, ctr: 488)] public igHandleMetaField _Localized_String_0x1e8 = new();
        [FieldAttr(nst: 504, ctr: 496)] public EOctaneRaceModes _E_Octane_Race_Modes;
        [FieldAttr(nst: 512, ctr: 504)] public igObject? _Localized_String_0x1f8 = new();
        [FieldAttr(nst: 520, ctr: 512)] public igHandleMetaField _Localized_String_0x200 = new();
        [FieldAttr(nst: 528, ctr: 520)] public bool _Bool_0x208;
        [FieldAttr(nst: 536, ctr: 528)] public igHandleMetaField _Gui_Animation_Tag_0x210 = new();
        [FieldAttr(nst: 544, ctr: 536)] public igHandleMetaField _Gui_Placeable_0x218 = new();
        [FieldAttr(nst: 552, ctr: 544)] public bool _Bool_0x220;
        [FieldAttr(nst: 560, ctr: 552)] public igHandleMetaField _Game_Sound_Music_Settings_0x228 = new();
        [FieldAttr(nst: 568, ctr: 560)] public igHandleMetaField _Game_Sound_Music_Settings_0x230 = new();
        [FieldAttr(nst: 576, ctr: 568)] public igHandleMetaField _Game_Sound_Music_Settings_0x238 = new();
        [FieldAttr(nst: 584, ctr: 576)] public igHandleMetaField _Game_Sound_Music_Settings_0x240 = new();
        [FieldAttr(nst: 592, ctr: 584)] public igHandleMetaField _Game_Sound_Music_Settings_0x248 = new();
        [FieldAttr(nst: 600, ctr: 592)] public igHandleMetaField _Game_Int_Variable = new();
        [FieldAttr(nst: 608, ctr: 600)] public igHandleMetaField _Game_Sound_Music_Settings_0x258 = new();
        [FieldAttr(nst: 616, ctr: 608)] public igHandleMetaField _Game_Bool_Variable_0x260 = new();
        [FieldAttr(nst: 624, ctr: 616)] public igHandleMetaField _Priority_Dsp_Override_Set_0x268 = new();
        [FieldAttr(nst: 632, ctr: 624)] public igObject? _InternalStore_prioritySetHandler_0x270 = new();
    }
}
