namespace Alchemy
{
    [ObjectAttr(nst: 656, ctr: 648, align: 4, metaType: typeof(igGuiVscBehavior))]
    public class Octane_RelicRace_Ranking_Root : igGuiVscBehavior
    {
        [FieldAttr(nst: 48, ctr: 40)] public igHandleMetaField _Gui_Animation_Tag_0x28 = new();
        [FieldAttr(nst: 56, ctr: 48)] public string? _String_0x30 = null;
        [FieldAttr(nst: 64, ctr: 56)] public igHandleMetaField _Gui_Placeable_0x38 = new();
        [FieldAttr(nst: 72, ctr: 64)] public string? _String_0x40 = null;
        [FieldAttr(nst: 80, ctr: 72)] public igHandleMetaField _Gui_Placeable_0x48 = new();
        [FieldAttr(nst: 88, ctr: 80)] public int _Int_0x50;
        [FieldAttr(nst: 92, ctr: 84)] public int _Int_0x54;
        [FieldAttr(nst: 96, ctr: 88)] public float _Float;
        [FieldAttr(nst: 100, ctr: 92)] public EZoneCollectibleType _E_Zone_Collectible_Type_0x5c;
        [FieldAttr(nst: 104, ctr: 96)] public bool _Bool_0x60;
        [FieldAttr(nst: 105, ctr: 97)] public bool _Bool_0x61;
        [FieldAttr(nst: 112, ctr: 104)] public igObject? _InternalStore_updateNodeUpdater = new();
        [FieldAttr(nst: 120, ctr: 112)] public EZoneCollectibleType _E_Zone_Collectible_Type_0x70;
        [FieldAttr(nst: 128, ctr: 120)] public igHandleMetaField _Gui_Placeable_0x78 = new();
        [FieldAttr(nst: 136, ctr: 128)] public string? _String_0x80 = null;
        [FieldAttr(nst: 144, ctr: 136)] public igHandleMetaField _Gui_Placeable_0x88 = new();
        [FieldAttr(nst: 152, ctr: 144)] public igHandleMetaField _Gui_Placeable_0x90 = new();
        [FieldAttr(nst: 160, ctr: 152)] public igHandleMetaField _Gui_Placeable_id_ey4u2hjp001 = new();
        [FieldAttr(nst: 168, ctr: 160)] public igHandleMetaField _Gui_Placeable_0xa0 = new();
        [FieldAttr(nst: 176, ctr: 168)] public igHandleMetaField _Gui_Placeable_id_ecyyyl71001 = new();
        [FieldAttr(nst: 184, ctr: 176)] public igHandleMetaField _Gui_Placeable_id_14sydewl001 = new();
        [FieldAttr(nst: 192, ctr: 184)] public igHandleMetaField _Gui_Placeable_id_14sydewl002 = new();
        [FieldAttr(nst: 200, ctr: 192)] public igHandleMetaField _Gui_Placeable_0xc0 = new();
        [FieldAttr(nst: 208, ctr: 200)] public igHandleMetaField _Gui_Animation_Tag_0xc8 = new();
        [FieldAttr(nst: 216, ctr: 208)] public igHandleMetaField _Gui_Animation_Tag_0xd0 = new();
        [FieldAttr(nst: 224, ctr: 216)] public bool _Bool_0xd8;
        [FieldAttr(nst: 232, ctr: 224)] public igHandleMetaField _Gui_Placeable_0xe0 = new();
        [FieldAttr(nst: 240, ctr: 232)] public igHandleMetaField _Gui_Placeable_0xe8 = new();
        [FieldAttr(nst: 248, ctr: 240)] public igHandleMetaField _Gui_Placeable_0xf0 = new();
        [FieldAttr(nst: 256, ctr: 248)] public bool _Bool_0xf8;
        [FieldAttr(nst: 264, ctr: 256)] public igHandleMetaField _Gui_Animation_Tag_0x100 = new();
        [FieldAttr(nst: 272, ctr: 264)] public igHandleMetaField _Gui_Placeable_id_9a0bg42e002 = new();
        [FieldAttr(nst: 280, ctr: 272)] public igHandleMetaField _Gui_Animation_Tag_0x110 = new();
        [FieldAttr(nst: 288, ctr: 280)] public igHandleMetaField _Gui_Placeable_0x118 = new();
        [FieldAttr(nst: 296, ctr: 288)] public igHandleMetaField _Sound_0x120 = new();
        [FieldAttr(nst: 304, ctr: 296)] public igHandleMetaField _Gui_Placeable_0x128 = new();
        [FieldAttr(nst: 312, ctr: 304)] public igHandleMetaField _Gui_Placeable_0x130 = new();
        [FieldAttr(nst: 320, ctr: 312)] public igHandleMetaField _Gui_Placeable_0x138 = new();
        [FieldAttr(nst: 328, ctr: 320)] public igHandleMetaField _Gui_Animation_Tag_0x140 = new();
        [FieldAttr(nst: 336, ctr: 328)] public igHandleMetaField _Gui_Placeable_0x148 = new();
        [FieldAttr(nst: 344, ctr: 336)] public igHandleMetaField _Gui_Placeable_0x150 = new();
        [FieldAttr(nst: 352, ctr: 344)] public igHandleMetaField _Gui_Placeable_0x158 = new();
        [FieldAttr(nst: 360, ctr: 352)] public igHandleMetaField _Gui_Placeable_0x160 = new();
        [FieldAttr(nst: 368, ctr: 360)] public igHandleMetaField _Gui_Placeable_0x168 = new();
        [FieldAttr(nst: 376, ctr: 368)] public igHandleMetaField _Gui_Placeable_0x170 = new();
        [FieldAttr(nst: 384, ctr: 376)] public igHandleMetaField _Gui_Placeable_0x178 = new();
        [FieldAttr(nst: 392, ctr: 384)] public igHandleMetaField _Gui_Placeable_0x180 = new();
        [FieldAttr(nst: 400, ctr: 392)] public igHandleMetaField _Gui_Placeable_0x188 = new();
        [FieldAttr(nst: 408, ctr: 400)] public igHandleMetaField _Gui_Placeable_0x190 = new();
        [FieldAttr(nst: 416, ctr: 408)] public igHandleMetaField _Entity_0x198 = new();
        [FieldAttr(nst: 424, ctr: 416)] public igHandleMetaField _Sound_0x1a0 = new();
        [FieldAttr(nst: 432, ctr: 424)] public igHandleMetaField _Gui_Placeable_0x1a8 = new();
        [FieldAttr(nst: 440, ctr: 432)] public igHandleMetaField _Material = new();
        [FieldAttr(nst: 448, ctr: 440)] public string? _String_0x1b8 = null;
        [FieldAttr(nst: 456, ctr: 448)] public igHandleMetaField _Localized_String_0x1c0 = new();
        [FieldAttr(nst: 464, ctr: 456)] public igHandleMetaField _Localized_String_0x1c8 = new();
        [FieldAttr(nst: 472, ctr: 464)] public igHandleMetaField _Localized_String_0x1d0 = new();
        [FieldAttr(nst: 480, ctr: 472)] public igHandleMetaField _Entity_0x1d8 = new();
        [FieldAttr(nst: 488, ctr: 480)] public igHandleMetaField _Gui_Placeable_0x1e0 = new();
        [FieldAttr(nst: 496, ctr: 488)] public igHandleMetaField _Gui_Placeable_0x1e8 = new();
        [FieldAttr(nst: 504, ctr: 496)] public igHandleMetaField _Gui_Placeable_0x1f0 = new();
        [FieldAttr(nst: 512, ctr: 504)] public igHandleMetaField _Gui_Placeable_0x1f8 = new();
        [FieldAttr(nst: 520, ctr: 512)] public igHandleMetaField _Gui_Placeable_0x200 = new();
        [FieldAttr(nst: 528, ctr: 520)] public igHandleMetaField _Gui_Animation_Tag_0x208 = new();
        [FieldAttr(nst: 536, ctr: 528)] public igHandleMetaField _Gui_Animation_Tag_0x210 = new();
        [FieldAttr(nst: 544, ctr: 536)] public igHandleMetaField _Gui_Placeable_0x218 = new();
        [FieldAttr(nst: 552, ctr: 544)] public igHandleMetaField _Gui_Project = new();
        [FieldAttr(nst: 560, ctr: 552)] public EGameMode _E_Game_Mode;
        [FieldAttr(nst: 564, ctr: 556)] public bool _Bool_0x22c;
        [FieldAttr(nst: 568, ctr: 560)] public igHandleMetaField _Gui_Animation_Tag_0x230 = new();
        [FieldAttr(nst: 576, ctr: 568)] public EZoneCollectibleType _E_Zone_Collectible_Type_0x238;
        [FieldAttr(nst: 580, ctr: 572)] public bool _Bool_0x23c;
        [FieldAttr(nst: 584, ctr: 576)] public igHandleMetaField _Gui_Placeable_0x240 = new();
        [FieldAttr(nst: 592, ctr: 584)] public igHandleMetaField _Gui_Placeable_0x248 = new();
        [FieldAttr(nst: 600, ctr: 592)] public igHandleMetaField _Gui_Placeable_id_huqn23ho002 = new();
        [FieldAttr(nst: 608, ctr: 600)] public igHandleMetaField _Gui_Placeable_0x258 = new();
        [FieldAttr(nst: 616, ctr: 608)] public igHandleMetaField _Gui_Placeable_0x260 = new();
        [FieldAttr(nst: 624, ctr: 616)] public igHandleMetaField _Gui_Placeable_0x268 = new();
        [FieldAttr(nst: 632, ctr: 624)] public igHandleMetaField _Gui_Placeable_0x270 = new();
        [FieldAttr(nst: 640, ctr: 632)] public string? _20e = null;
        [FieldAttr(nst: 648, ctr: 640)] public int _20f;
    }
}
