namespace Alchemy
{
    [ObjectAttr(nst: 712, ctr: 704, align: 4, metaType: typeof(igGuiVscBehavior))]
    public class common_TimeTrial_Root : igGuiVscBehavior
    {
        [FieldAttr(nst: 40, ctr: 32)] public igObject? _InternalStore_updateNodeUpdater = new();
        [FieldAttr(nst: 48, ctr: 40)] public igObject? _InternalStore__counter = new();
        [FieldAttr(nst: 56, ctr: 48)] public bool _Bool;
        [FieldAttr(nst: 64, ctr: 56)] public igObject? _InternalStore__timer = new();
        [FieldAttr(nst: 72, ctr: 64)] public igHandleMetaField _Gui_Placeable_0x48 = new();
        [FieldAttr(nst: 80, ctr: 72)] public int _Int_0x50;
        [FieldAttr(nst: 84, ctr: 76)] public int _Int_0x54;
        [FieldAttr(nst: 88, ctr: 80)] public int _Int_0x58;
        [FieldAttr(nst: 92, ctr: 84)] public float _Float_0x5c;
        [FieldAttr(nst: 96, ctr: 88)] public igHandleMetaField _Gui_Placeable_0x60 = new();
        [FieldAttr(nst: 104, ctr: 96)] public igHandleMetaField _Gui_Placeable_0x68 = new();
        [FieldAttr(nst: 112, ctr: 104)] public igHandleMetaField _Gui_Placeable_0x70 = new();
        [FieldAttr(nst: 120, ctr: 112)] public igHandleMetaField _Localized_String_0x78 = new();
        [FieldAttr(nst: 128, ctr: 120)] public igHandleMetaField _Localized_String_0x80 = new();
        [FieldAttr(nst: 136, ctr: 128)] public igHandleMetaField _Gui_Placeable_0x88 = new();
        [FieldAttr(nst: 144, ctr: 136)] public igHandleMetaField _Gui_Placeable_0x90 = new();
        [FieldAttr(nst: 152, ctr: 144)] public igHandleMetaField _Gui_Placeable_0x98 = new();
        [FieldAttr(nst: 160, ctr: 152)] public igHandleMetaField _Localized_String_0xa0 = new();
        [FieldAttr(nst: 168, ctr: 160)] public string? _String_0xa8 = null;
        [FieldAttr(nst: 176, ctr: 168)] public igHandleMetaField _Gui_Animation_Tag_0xb0 = new();
        [FieldAttr(nst: 184, ctr: 176)] public igHandleMetaField _Gui_Animation_Tag_0xb8 = new();
        [FieldAttr(nst: 192, ctr: 184)] public igHandleMetaField _Gui_Animation_Tag_0xc0 = new();
        [FieldAttr(nst: 200, ctr: 192)] public igHandleMetaField _Gui_Animation_Tag_0xc8 = new();
        [FieldAttr(nst: 208, ctr: 200)] public igHandleMetaField _Gui_Animation_Tag_0xd0 = new();
        [FieldAttr(nst: 216, ctr: 208)] public igObject? _InternalStore_listener = new();
        [FieldAttr(nst: 224, ctr: 216)] public igHandleMetaField _Gui_Animation_Tag_0xe0 = new();
        [FieldAttr(nst: 232, ctr: 224)] public igHandleMetaField _Gui_Placeable_0xe8 = new();
        [FieldAttr(nst: 240, ctr: 232)] public igHandleMetaField _InternalStore_project = new();
        [FieldAttr(nst: 248, ctr: 240)] public igHandleMetaField _Gui_Placeable_0xf8 = new();
        [FieldAttr(nst: 256, ctr: 248)] public float _Float_0x100;
        [FieldAttr(nst: 260, ctr: 252)] public float _Float_0x104;
        [FieldAttr(nst: 264, ctr: 256)] public int _Int_0x108;
        [FieldAttr(nst: 272, ctr: 264)] public igHandleMetaField _Gui_Animation_Tag_0x110 = new();
        [FieldAttr(nst: 280, ctr: 272)] public igHandleMetaField _Localized_String_0x118 = new();
        [FieldAttr(nst: 288, ctr: 280)] public igHandleMetaField _Gui_Animation_Tag_0x120 = new();
        [FieldAttr(nst: 296, ctr: 288)] public igHandleMetaField _Gui_Animation_Tag_0x128 = new();
        [FieldAttr(nst: 304, ctr: 296)] public int _InternalStore__internalCounter;
        [FieldAttr(nst: 312, ctr: 304)] public igObject? _Localized_String_0x138 = new();
        [FieldAttr(nst: 320, ctr: 312)] public igHandleMetaField _Localized_String_List = new();
        [FieldAttr(nst: 328, ctr: 320)] public igHandleMetaField _Gui_Animation_Tag_0x148 = new();
        [FieldAttr(nst: 336, ctr: 328)] public igHandleMetaField _Gui_Animation_Tag_0x150 = new();
        [FieldAttr(nst: 344, ctr: 336)] public igHandleMetaField _Gui_Animation_Tag_0x158 = new();
        [FieldAttr(nst: 352, ctr: 344)] public float _Float_0x160;
        [FieldAttr(nst: 360, ctr: 352)] public igHandleMetaField _Zone_Info = new();
        [FieldAttr(nst: 368, ctr: 360)] public float _Float_0x170;
        [FieldAttr(nst: 372, ctr: 364)] public CTimeTrialNodes.ETimeTrialRelic _Time_Trial_Nodes_E_Time_Trial_Relic;
        [FieldAttr(nst: 376, ctr: 368)] public igObject? _InternalStore__gate = new();
        [FieldAttr(nst: 384, ctr: 376)] public igHandleMetaField _Open_Keyboard_Params = new();
        [FieldAttr(nst: 392, ctr: 384)] public int _Int_0x188;
        [FieldAttr(nst: 396, ctr: 388)] public int _Int_0x18c;
        [FieldAttr(nst: 400, ctr: 392)] public int _Int_0x190;
        [FieldAttr(nst: 408, ctr: 400)] public igHandleMetaField _Gui_Placeable_0x198 = new();
        [FieldAttr(nst: 416, ctr: 408)] public igHandleMetaField _Gui_Placeable_0x1a0 = new();
        [FieldAttr(nst: 424, ctr: 416)] public igHandleMetaField _Gui_Placeable_0x1a8 = new();
        [FieldAttr(nst: 432, ctr: 424)] public int _Int_0x1b0;
        [FieldAttr(nst: 436, ctr: 428)] public EZoneCollectibleType _E_Zone_Collectible_Type;
        [FieldAttr(nst: 440, ctr: 432)] public igHandleMetaField _Entity = new();
        [FieldAttr(nst: 448, ctr: 440)] public igHandleMetaField _Gui_Animation_Tag_0x1c0 = new();
        [FieldAttr(nst: 456, ctr: 448)] public igHandleMetaField _Gui_Animation_Tag_0x1c8 = new();
        [FieldAttr(nst: 464, ctr: 456)] public igHandleMetaField _Fade_Out_Preset_Data = new();
        [FieldAttr(nst: 472, ctr: 464)] public igHandleMetaField _Bitmap_Font = new();
        [FieldAttr(nst: 480, ctr: 472)] public string? _String_0x1e0 = null;
        [FieldAttr(nst: 488, ctr: 480)] public igHandleMetaField _Game_String_Variable_0x1e8 = new();
        [FieldAttr(nst: 496, ctr: 488)] public igHandleMetaField _Game_String_Variable_0x1f0 = new();
        [FieldAttr(nst: 504, ctr: 496)] public igHandleMetaField _Character_Info_Hash_Table = new();
        [FieldAttr(nst: 512, ctr: 504)] public string? _String_0x200 = null;
        [FieldAttr(nst: 520, ctr: 512)] public int _igIntMetaField2e7;
        [FieldAttr(nst: 524, ctr: 516)] public int _igIntMetaField2e8;
        [FieldAttr(nst: 528, ctr: 520)] public int _igIntMetaField2e9;
        [FieldAttr(nst: 532, ctr: 524)] public int _igIntMetaField2ea;
        [FieldAttr(nst: 536, ctr: 528)] public int _igIntMetaField2eb;
        [FieldAttr(nst: 544, ctr: 536)] public string? _igStringMetaField2ec = null;
        [FieldAttr(nst: 552, ctr: 544)] public string? _igStringMetaField2ed = null;
        [FieldAttr(nst: 560, ctr: 552)] public string? _igStringMetaField2ee = null;
        [FieldAttr(nst: 568, ctr: 560)] public int _igIntMetaField35c;
        [FieldAttr(nst: 572, ctr: 564)] public int _igIntMetaField35d;
        [FieldAttr(nst: 576, ctr: 568)] public int _igIntMetaField35e;
        [FieldAttr(nst: 580, ctr: 572)] public int _igIntMetaField35f;
        [FieldAttr(nst: 584, ctr: 576)] public int _igIntMetaField360;
        [FieldAttr(nst: 592, ctr: 584)] public string? _igStringMetaField361 = null;
        [FieldAttr(nst: 600, ctr: 592)] public string? _igStringMetaField362 = null;
        [FieldAttr(nst: 608, ctr: 600)] public string? _igStringMetaField363 = null;
        [FieldAttr(nst: 616, ctr: 608)] public int _igIntMetaField3d1;
        [FieldAttr(nst: 620, ctr: 612)] public int _igIntMetaField3d2;
        [FieldAttr(nst: 624, ctr: 616)] public int _igIntMetaField3d3;
        [FieldAttr(nst: 628, ctr: 620)] public int _igIntMetaField3d4;
        [FieldAttr(nst: 632, ctr: 624)] public int _igIntMetaField3d5;
        [FieldAttr(nst: 640, ctr: 632)] public string? _igStringMetaField3d6 = null;
        [FieldAttr(nst: 648, ctr: 640)] public string? _igStringMetaField3d7 = null;
        [FieldAttr(nst: 656, ctr: 648)] public string? _igStringMetaField3d8 = null;
        [FieldAttr(nst: 664, ctr: 656)] public int _igIntMetaField446;
        [FieldAttr(nst: 668, ctr: 660)] public int _igIntMetaField447;
        [FieldAttr(nst: 672, ctr: 664)] public int _igIntMetaField448;
        [FieldAttr(nst: 676, ctr: 668)] public int _igIntMetaField449;
        [FieldAttr(nst: 680, ctr: 672)] public int _igIntMetaField44a;
        [FieldAttr(nst: 688, ctr: 680)] public string? _igStringMetaField44b = null;
        [FieldAttr(nst: 696, ctr: 688)] public string? _igStringMetaField44c = null;
        [FieldAttr(nst: 704, ctr: 696)] public string? _igStringMetaField44d = null;
    }
}
