namespace Alchemy
{
    [ObjectAttr(1408, 16)]
    public class CAirVehicleCamera : CConstrainedCamera
    {
        [FieldAttr(432)] public float _followHeight = 600.0f;
        [FieldAttr(436)] public float _followDistance = 800.0f;
        [FieldAttr(440)] public float _lookAheadDistance = 400.0f;
        [FieldAttr(444)] public float _vehicleTurnRate = 100.0f;
        [FieldAttr(448)] public float _vehicleClimbRate = 2000.0f;
        [FieldAttr(452)] public float _followDistanceOnTurnModifier = -100.0f;
        [FieldAttr(456)] public float _safeAreaVerticalOffsetOnClimbModifier;
        [FieldAttr(460)] public float _safeAreaVerticalOffsetOnDescendModifier = 0.6f;
        [FieldAttr(464)] public float _safeAreaHorizontalOffsetOnTurnModifier = 1.0f;
        [FieldAttr(468)] public float _rotationDampingFactor = 20.0f;
        [FieldAttr(472)] public EigEaseType _turnDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(476)] public float _heightDampingFactor = 20.0f;
        [FieldAttr(480)] public EigEaseType _heightDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(484)] public float _screenSafeAreaOffsetDampingFactor = 20.0f;
        [FieldAttr(488)] public EigEaseType _screenSafeAreaOffsetDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(492)] public float _followDistanceDampingFactor = 20.0f;
        [FieldAttr(496)] public EigEaseType _followDistanceDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(500)] public EPlayerId _playerId = EPlayerId.EPLAYERID_NONE;
        [FieldAttr(504)] public CCameraScreenSafeArea? _offsetScreenSafeArea;
        [FieldAttr(512)] public igVec3fMetaField _previousDirectionFromVehicleToCamera = new();
        [FieldAttr(524)] public igVec2fMetaField _previousScreenSafeAreaOffset = new();
        [FieldAttr(532)] public float _previousVehicleHeight;
        [FieldAttr(536)] public igVec3fMetaField _baseToMinimalSpeed = new();
        [FieldAttr(548)] public igVec3fMetaField _baseToMaximalSpeed = new();
        [FieldAttr(560)] public igVec3fMetaField _addTurnToMinimalSpeed = new();
        [FieldAttr(572)] public igVec3fMetaField _addTurnToMaximalSpeed = new();
        [FieldAttr(584)] public float _blendHorizontalFactor = 0.2f;
        [FieldAttr(588)] public float _blendVerticalFactor = 0.1f;
        [FieldAttr(592)] public float _blendTotalVelocityFactor = 0.2f;
        [FieldAttr(596)] public float _blendTurnFactor = 0.1f;
        [FieldAttr(600)] public float _maxTotalSpeed = 3000.0f;
        [FieldAttr(604)] public float _maxTurnRate = 100.0f;
        [FieldAttr(608)] public float _directionDampingFactor = 0.25f;
        [FieldAttr(612)] public bool _lookAtSupport;
        [FieldAttr(616)] public float _pitchAtMinimalSpeed;
        [FieldAttr(620)] public float _pitchAtMaximalSpeed;
        [FieldAttr(624)] public float _rearViewRelativeDistance = 0.61f;
        [FieldAttr(628)] public igVec3fMetaField _combatBaseToMinimalSpeed = new();
        [FieldAttr(640)] public igVec3fMetaField _combatBaseToMaximalSpeed = new();
        [FieldAttr(652)] public float _combatPitchAtMinimalSpeed;
        [FieldAttr(656)] public float _combatPitchAtMaximalSpeed;
        [FieldAttr(660)] public EXBUTTON _switchParametersButton = EXBUTTON.L3;
        [FieldAttr(664)] public float _switchTransitionSpeed = 1.5f;
        [FieldAttr(672)] public CVehicleCameraZoomCollision? _zoomCollision;
        [FieldAttr(680)] public CVehicleCameraPanCollision? _upPanCollision;
        [FieldAttr(688)] public igVec3fMetaField _directionDampingForwardVelocity = new();
        [FieldAttr(700)] public igVec3fMetaField _directionDampingUpVelocity = new();
        [FieldAttr(712)] public igVec3fMetaField _dampenedForward = new();
        [FieldAttr(724)] public igVec3fMetaField _dampenedUp = new();
        [FieldAttr(736)] public bool _previousTargetInit;
        [FieldAttr(740)] public float _currentSpeedRatio;
        [FieldAttr(744)] public float _previousTotalRatioVel;
        [FieldAttr(748)] public float _currentTurnRatio;
        [FieldAttr(752)] public float _previousTurnRatioVel;
        [FieldAttr(768)] public igMatrix44fMetaField _previousTargetTransform = new();
        [FieldAttr(832)] public CTransformMetaField _previousTransform = new();
        [FieldAttr(860)] public igVec3fMetaField _previousCameraTarget = new();
        [FieldAttr(872)] public igVec3fMetaField _previousCameraPositionVelocity = new();
        [FieldAttr(884)] public float _cameraPositionDampingFactor = 20.0f;
        [FieldAttr(888)] public igVec3fMetaField _previousCameraTargetVelocity = new();
        [FieldAttr(900)] public float _cameraTargetDampingFactor = 20.0f;
        [FieldAttr(904)] public float _previousVehicleCameraHeightOffset;
        [FieldAttr(908)] public float _previousVehicleCameraYawRotation;
        [FieldAttr(912)] public igVec2fMetaField _previousCameraPitchYaw = new();
        [FieldAttr(920)] public igVec2fMetaField _previousCameraPitchYawVelocity = new();
        [FieldAttr(928)] public float _previousCameraRoll;
        [FieldAttr(932)] public float _previousCameraRollVelocity;
        [FieldAttr(936)] public float _followPitchRatio = 0.75f;
        [FieldAttr(940)] public float _cameraPitchDampingFactor = 0.1f;
        [FieldAttr(944)] public float _cameraYawDampingFactor = 0.1f;
        [FieldAttr(948)] public float _cameraRollDampingFactor = 0.1f;
        [FieldAttr(952)] public float _verticalFollowAngle = 1.5f;
        [FieldAttr(956)] public float _followDistanceMax = 1000.0f;
        [FieldAttr(960)] public float _followDistanceMin = 600.0f;
        [FieldAttr(964)] public igVfxRangedCurveMetaField _followDistanceCurve = new();
        [FieldAttr(1048)] public float _rotationOffsetFromForward;
        [FieldAttr(1052)] public float _cameraRollMax = 8.0f;
        [FieldAttr(1056)] public float _cameraRollMin;
        [FieldAttr(1060)] public igVfxRangedCurveMetaField _cameraRollCurve = new();
        [FieldAttr(1144)] public float _cameraYawAngleWobble;
        [FieldAttr(1148)] public float _cameraYawMax;
        [FieldAttr(1152)] public float _cameraYawMin;
        [FieldAttr(1156)] public igVfxRangedCurveMetaField _cameraYawCurve = new();
        [FieldAttr(1240)] public bool _cameraAlwaysPitchAroundVehicle = true;
        [FieldAttr(1244)] public float _cameraPitchAngleWobble;
        [FieldAttr(1248)] public float _cameraPitchMax;
        [FieldAttr(1252)] public float _cameraPitchMin;
        [FieldAttr(1256)] public igVfxRangedCurveMetaField _cameraPitchCurve = new();
        [FieldAttr(1340)] public bool _cameraChecksForCollisions;
        [FieldAttr(1344)] public float _angleToStopFollowingVehicle = 90.0f;
        [FieldAttr(1348)] public float _angleToStopLockingCamera = 90.0f;
        [FieldAttr(1352)] public float _epicJumpFov = 100.0f;
        [FieldAttr(1356)] public float _addedBoostFovRadians;
        [FieldAttr(1360)] public bool _zoomCollided;
        [FieldAttr(1361)] public bool _upPanCollided;
        [FieldAttr(1362)] public bool _useCombatParameters;
        [FieldAttr(1364)] public igVec3fMetaField _currentBaseToMinimalSpeed = new();
        [FieldAttr(1376)] public igVec3fMetaField _currentBaseToMaximalSpeed = new();
        [FieldAttr(1388)] public float _currentPitchAtMinimalSpeed;
        [FieldAttr(1392)] public float _currentPitchAtMaximalSpeed;
    }
}
